/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Stitch full palette ─────────────────────────────────────
        "surface":                     "#0d0a27",
        "surface-dim":                 "#0d0a27",
        "surface-bright":              "#2a2653",
        "surface-container-lowest":    "#000000",
        "surface-container-low":       "#120f2f",
        "surface-container":           "#181538",
        "surface-container-high":      "#1e1a41",
        "surface-container-highest":   "#24204a",
        "surface-variant":             "#24204a",
        "on-surface":                  "#e7e2ff",
        "on-surface-var":              "#aca7cc",
        "on-surface-variant":          "#aca7cc",
        "on-background":               "#e7e2ff",
        "background":                  "#0d0a27",
        "inverse-on-surface":          "#555172",
        "inverse-surface":             "#fcf8ff",
        "primary":                     "#97a9ff",
        "primary-dim":                 "#8197ff",
        "primary-fixed":               "#859aff",
        "primary-fixed-dim":           "#748cf9",
        "primary-container":           "#859aff",
        "on-primary":                  "#002283",
        "on-primary-container":        "#001867",
        "on-primary-fixed":            "#000000",
        "on-primary-fixed-variant":    "#00207e",
        "inverse-primary":             "#3d56c0",
        "surface-tint":                "#97a9ff",
        "secondary":                   "#c99af8",
        "secondary-dim":               "#bb8de9",
        "secondary-fixed":             "#e4c6ff",
        "secondary-fixed-dim":         "#dab4ff",
        "secondary-container":         "#5c3187",
        "on-secondary":                "#42146d",
        "on-secondary-container":      "#e3c4ff",
        "on-secondary-fixed":          "#481c73",
        "on-secondary-fixed-variant":  "#663c92",
        "tertiary":                    "#f8acff",
        "tertiary-dim":                "#e589f0",
        "tertiary-fixed":              "#f496ff",
        "tertiary-fixed-dim":          "#e589f0",
        "tertiary-container":          "#f496ff",
        "on-tertiary":                 "#6b167b",
        "on-tertiary-container":       "#600570",
        "on-tertiary-fixed":           "#3d0049",
        "on-tertiary-fixed-variant":   "#6a157a",
        "error":                       "#ff6e84",
        "error-dim":                   "#d73357",
        "error-container":             "#a70138",
        "on-error":                    "#490013",
        "on-error-container":          "#ffb2b9",
        "outline":                     "#757294",
        "outline-var":                 "#474464",
        "outline-variant":             "#474464",
        "success":                     "#4ade80",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "'Fira Code'", "monospace"],
        headline: ["Inter", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      animation: {
        "float":        "float 3s ease-in-out infinite",
        "shimmer":      "shimmer 2.5s linear infinite",
        "shimmer-bar":  "shimmerBar 2s linear infinite",
        "fade-in-up":   "fadeInUp 0.4s ease",
        "pulse-dot":    "pulseDot 2s ease-in-out infinite",
      },
      keyframes: {
        float:      { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-10px)" } },
        shimmer:    { "0%": { backgroundPosition: "200% center" }, "100%": { backgroundPosition: "-200% center" } },
        shimmerBar: { "0%": { backgroundPosition: "200% 0" }, "100%": { backgroundPosition: "-200% 0" } },
        fadeInUp:   { from: { opacity: "0", transform: "translateY(16px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        pulseDot:   { "0%,100%": { opacity: "1" }, "50%": { opacity: "0.3" } },
      },
    },
  },
  plugins: [],
}

